name: metaGP
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - configparser
  - fastqc
  - cutadapt
  - kneaddata
  - bowtie2
  - trimmomatic
  - trf
  - seaborn
  - metaphlan
  - scikit-bio
  - statannotations
#  - samtools
#  - ucsc-bedsort
#  - ucsc-bedgraphtobigwig
#  - bedtools
#  - deeptools
#  - homer
#  - seacr
