name: metaGP
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - configparser
  - bowtie2
  - fastqc
  - samtools
  - ucsc-bedsort
  - ucsc-bedgraphtobigwig
  - bedtools
  - deeptools
  - homer
  - seacr
